### ISSUE TITLE
ajardin:synchro image

### ISSUE THREAD

**Issue by chuongnh3atgmaildotcom** [ajardin/origami-source#316]
Thanks for this tool, it looks really helpful. Just one question.

What is the purpose of **ajardin/synchro** image and what does it contain?

I didn't found more info in https://github.com/ajardin/docker-images neither https://hub.docker.com/r/ajardin/synchro/

**Comment by ajardin** [comment]
Hello and thanks for your message!

This is my custom image used for the [Mutagen](https://github.com/mutagen-io/mutagen) synchronization. Basically, I created a container and a volume called `synchro` to [share the source code](https://github.com/ajardin/origami-source/blob/master/src/Middleware/Binary/Mutagen.php#L41) from the OS to the Docker environments. The volume is then filled by Mutagen, allowing to share the source code to the `nginx` and `php` containers.

This image does not contain anything fancy, here is the associated Dockerfile.
```
FROM alpine:latest

LABEL org.opencontainers.image.authors="Alexandre Jardin <info@ajardin.fr>"
LABEL org.opencontainers.image.title="Image with a new user/group to be used with Mutagen."
LABEL org.opencontainers.image.description=""
LABEL org.opencontainers.image.source="https://github.com/ajardin/docker-images/blob/master/common/synchro/Dockerfile"

# Create a new user/group with the same ID than in "nginx" and "php" services
RUN \
    addgroup -g 1000 -S synchro && \
    adduser -u 1000 -D -S -G synchro synchro

CMD ["tail", "-f", "/dev/null"]

```

Why is it no longer present in my dedicated repository?.. Well, because I forgot to put it back! 😅 

To be completely honest, Mutagen allows for better file sharing performance, but it makes day-to-day management more complex and sometimes leads to other problems such as excessive consumption of host system resources. That's why I removed it at one point and continue to challenge it to see if there is a more appropriate solution.

If you don't mind, could you tell me what kind of environment you are using on which OS?

**Comment by chuongnh3atgmaildotcom** [comment]
Thanks for your answer.

I'm trying to setup orocommerce on Ubuntu and want it to work on mac too. 

For me mutagen is a big plus, without it my dockerized setup is unusable on mac. But I can imagine the hassle of managing the sessions. Mutagen has some improvement including yaml config file - worth to look at https://mutagen.io/documentation/orchestration

**Comment by ajardin** [comment]
Mutagen (or something similar) is indeed mandatory when working on macOS with projects containing many files, unfortunately... 😞 

I've already done some testing with the new Docker Compose integration, which still requires using the beta version. But we encountered several issues (e.g. https://github.com/mutagen-io/mutagen/issues/243) that finally led me to go back to the manual management of Mutagen sessions.
